name: Maintain services/pods on EKS

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        kubectl-version: "latest"

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name my-eks-cluster

    - name: Install Helm
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Check Helm
      run: which helm

    - name: Install ALB
      run: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
          --set clusterName=my-eks-cluster \
          --set serviceAccount.create=false \
          --set region=${{ secrets.AWS_REGION }} \
          --set vpcId=${{ secrets.AWS_VPC_ID }} \
          -n kube-system

    - name: Apply kubernetes yaml files
      working-directory: ./yamle
      run: kubectl apply -f .

    - name: Force update
      run: kubectl rollout restart deployment/frontend-deployment

