name: Test kubernetes

on:
  workflow_dispatch

jobs:
  test:
    name: Test eks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        kubectl-version: "latest"

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name my-eks-cluster \
          --region ${{ secrets.AWS_REGION }}
      
    - name: Get map config
      run: kubectl -n kube-system get configmap aws-auth -o yaml
    - name: Describe subnets
      run: aws ec2 describe-subnets --filters Name=tag:kubernetes.io/cluster/my-eks-cluster,Values=shared

    - name: Get Pods
      run: kubectl get pod -o wide

    - name: Get SVC
      run: kubectl get svc

    - name: Describe ALB
      run: kubectl get ingress
    
    - name: Get pods
      run: kubectl get pods -n kube-system

    - name: Get ingress
      run: kubectl get ingressclass

    - name: Describe ingress
      run: kubectl describe ingress main-ingress-1

    - name: Get Logs
      run: kubectl logs deployment/aws-load-balancer-controller -n kube-system

    - name: Check if oidc exist
      run: aws eks describe-cluster --name my-eks-cluster --query "cluster.identity.oidc.issuer" --output text

    - name: Install EKS CTL
      run: |
        curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
        | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bi
    
    - name: Assosciate IAM Provider
      run: |
        eksctl utils associate-iam-oidc-provider \
          --region ${{ secrets.AWS_REGION }} \
          --cluster my-eks-cluster \
          --approve

