name: Test kubernetes

on:
  workflow_dispatch

jobs:
  test:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        kubectl-version: "latest"

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name my-eks-cluster \
          --region ${{ secrets.AWS_REGION }}
      
    - name: Get map config
      run: kubectl -n kube-system get configmap aws-auth -o yaml
    - name: Describe subnets
      run: aws ec2 describe-subnets --filters Name=tag:kubernetes.io/cluster/my-eks-cluster,Values=shared

    - name: Get Pods
      run: kubectl get pod -o wide
